### ISSUE TITLE
Error when using ko.toJSON(viewModel)

### ISSUE THREAD

**Issue by hungao** [adrotec/knockout-file-bindings#1]
Uncaught DOMException: Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('file') does not support selection.code: 11message: "Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('file') does not support selection."name: "InvalidStateError"stack: "Error: Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('file') does not support selection.↵    at Error (native)↵    at http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1904:60↵    at visitPropertiesOrArrayEntries (http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1935:17)↵    at mapJsObjectGraph (http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1903:9)↵    at http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1917:27↵    at visitPropertiesOrArrayEntries (http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1935:17)↵    at mapJsObjectGraph (http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1903:9)↵    at http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1917:27↵    at visitPropertiesOrArrayEntries (http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1935:17)↵    at mapJsObjectGraph (http://localhost:1404/Scripts/knockout-3.2.0.debug.js:1903:9)"**proto**: DOMException knockout-3.2.0.debug.js:1904(anonymous function) knockout-3.2.0.debug.js:1904visitPropertiesOrArrayEntries knockout-3.2.0.debug.js:1935mapJsObjectGraph knockout-3.2.0.debug.js:1903(anonymous function) knockout-3.2.0.debug.js:1917visitPropertiesOrArrayEntries knockout-3.2.0.debug.js:1935mapJsObjectGraph knockout-3.2.0.debug.js:1903(anonymous function) knockout-3.2.0.debug.js:1917visitPropertiesOrArrayEntries knockout-3.2.0.debug.js:1935mapJsObjectGraph knockout-3.2.0.debug.js:1903ko.toJS knockout-3.2.0.debug.js:1879ko.toJSON knockout-3.2.0.debug.js:1888(anonymous function) VM659:2InjectedScript._evaluateOn VM562:732InjectedScript._evaluateAndWrap VM562:665InjectedScript.evaluate

**Comment by michaleq91** [comment]
It doesn't work for me. Still have the same error.

**Comment by mrsafraz** [comment]
@michaleq91 can you please open another issue and explain what you encounter. I think you might have a different issue

**Comment by michaleq91** [comment]
No, it was my fault in the end. Works like a charm :)
Thank you for quick response
