### ISSUE TITLE
Choose file button can only be pressed if clicked directly on text

### ISSUE THREAD

**Issue by marcelgruber** [adrotec/knockout-file-bindings#10]
The edges of the button don't seem to work, which can give the impression that it's broken if not clicked in the right area :)

**Comment by safrazik** [comment]
Sorry for the very late response. Did you make it work? Did you find a solution yet? In which browsers you see this issue?

**Comment by marcelgruber** [comment]
No worries. I made it work by simply expanding the height of the input element. This issue was in an up to date version of Chrome.
