### ISSUE TITLE
Issue loading data URL from server into file input

### ISSUE THREAD

**Issue by mccallsolutions** [adrotec/knockout-file-bindings#20]
I can't seem to load my data URL into the file data url without getting this error. Can you help me out?

knockout-3.4.0.debug.js:3326 Uncaught TypeError: Unable to process binding "with: function (){return viewModel }"
Message: Unable to process binding "with: function (){return UserInfo }"
Message: Unable to process binding "with: function (){return Property }"
Message: Unable to process binding "fileInput: function (){return $root.usersettings().viewModel().fileData }"
Message: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

This is my code:

`function serverFileData(data) {
        var self = this;
        
        self.dataURL = ko.observable(data.dataUrl);
        self.file = ko.observable(data.file);
    }

self.fileData = ko.observable(new serverFileData(data.fileData));`

data.dataUrl = "data:image/jpeg;base64,/9j/4AAQSkZJRgABA..."
data.file = { size: 2374844, type: "image/png" }

**Comment by safrazik** [comment]
```javascript
self.file = ko.observable(/* data.file */); // this property will be filled when a user selects a file
```

**Comment by scottsanzo** [comment]
To get rid of the "not of type 'Blob'" error, you need to check to see if the file is an instance of Blob  before the reader reads the file. I.E. in the fileInput binding handler's update method, replace "reader[method](file);" with: 
" (file instanceof Blob)
     [method](file);"

If you truly need to load the file data (presumably so it can be uploaded) you'll need to convert your base64 string into a Blob. This link is helpful, but it's not an efficient or particularly graceful process:
http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript
Hope that helps

**Comment by safrazik** [comment]
Closing the issue because setting `file` property is considered a hack. As @scottsanzo suggests, converting into Blob could work. Interesting! Thanks for letting know
