### ISSUE TITLE
CDN + TypeScript TypeDefintion

### ISSUE THREAD

**Issue by apumex** [adrotec/knockout-file-bindings#24]
I like this project, but I dont see any CDN hosting it. Can we get this added to any one CDN.

Also was not able to find the TypeDefinition. Can we get the typedefinition for the same.

Thanks

**Comment by gregveres** [comment]
@apumex did you get a typescript definition file for this? Did you create one? I am about to start using it with typescript, so if one exists that would save me writing one. 

Thanks
Greg
