### ISSUE TITLE
Object does not support method 'readAsBinaryString'

### ISSUE THREAD

**Issue by jeanie77** [adrotec/knockout-file-bindings#26]
I'm having an issue with both 1.0.0 and 1.1.0 releases.
If I configure my view model for a single file, as explained in Advanced usage:

`viewModel.fileData = ko.observable({`
`        file: ko.observable(),`
`        binaryString: ko.observable(),`
`        dataURL: ko.observable()`
`});`

an issue is raised at knockout-file-bindings, line 200: Object does not support method 'readAsBinaryString'.
Value of reader[method] is undefined, hence the error.

**Comment by jeanie77** [comment]
This is because I'm using IE11 and FileReader API is not fully supported:
[http://caniuse.com/#search=FileReader](http://caniuse.com/#search=FileReader)
Unfortunately, IE11 does not support exactly readAsBinaryString.

I've updated viewModel using 'base64String' instead of 'binaryString' and it works!

**Comment by safrazik** [comment]
@jeanie77 thanks for the info. a warning should be put on the documentation. It would be helpful for other users.
