### ISSUE TITLE
Some way for restrict file types

### ISSUE THREAD

**Issue by bogutskyy** [adrotec/knockout-file-bindings#28]
It would be nice to have some way for restrict file types during select or drag. For example, it's possible to allow select only images using accept attribute of input element, but in the same time user can drag any of file type.

**Comment by equisgroup** [comment]
Would be a nice feature.  AS far as documentation goes and use case there isn't any default way to do it but maybe adding ko.validation and using it over the viewmodel dataURL variable you could manage to do it.

I can't try it at the moment but looks like a viable option

**Comment by viqashussain** [comment]
You can use this custom KO validation:

ko.validation.rules["fileFormat"] = {
            async: false,
                validator: function (val, params) {
                if (val === "")
                {
                    return true;
                }
                if (val === undefined || val === null)
                {
                    return false;
                }
                var regExp = /(?:\.([^.]+))?$/;
                var fileType = regExp.exec(val)[1].toLowerCase();

                return params.supportedFileTypes.indexOf(fileType) !== -1;
            },
            message: "The file you are attaching is not a supported file format."
        };

Then validate the full file name like so:

attachedFileName.extend({
                fileFormat: { supportedFileTypes: ["doc", "docx", "
})
