### ISSUE TITLE
Issues with size of file being uploaded

### ISSUE THREAD

**Issue by viqashussain** [adrotec/knockout-file-bindings#29]
I've found that when I'm using this binding to upload a file that is larger than about 20mb, then the base64String is often not set. I believe the binding takes too long to set this value, and when I use it, it is undefined. If I wait for a few seconds, then the value for base64String is eventually set.

**Comment by safrazik** [comment]
using base64String for larger files is not recommended. especially it will kill your mobile browser. The library itself cannot improve the performance of that as it is browser dependent.
