### ISSUE TITLE
fileData().text does not populate 

### ISSUE THREAD

**Issue by rrhyne** [adrotec/knockout-file-bindings#3]
First, thanks for the great set of bindings. I think I've spotted an issue though in text population.  When uploading a text document the base64String is returned, but text seems not to be.

I've prepared a codepen based on your example:

http://codepen.io/anon/pen/VYMBxo

Thanks!

**Comment by mrsafraz** [comment]
Yes, everything except `base64String`, `file` and `dataURL` doesn't seem to trigger events. I am looking at the issue. If you have tried to fix it, send me a pull request.

**Comment by mrsafraz** [comment]
The issue has been fixed. Please check the updated version and confirm if it's working.

**Comment by rrhyne** [comment]
I can confirm this fix worked, thanks!
