### ISSUE TITLE
base64StringArray Size

### ISSUE THREAD

**Issue by equisgroup** [adrotec/knockout-file-bindings#30]
I am using base64StringArray, base64String but on some cases it has more items than fileArray and dataURLArray.

Usually it happens when i add 3 files, clear and then add 2 files for example

I notice that this library generates the base64String, is there a way to trigger the base64String update and detect when is finished?

**Comment by equisgroup** [comment]
I read an closed issue. Looks like there aren't any mention to this at help but maybe i'm wrong. will test and close if solve the problem.

viewModel.fileData.subscribe(function (fileData) {
// fileData has changed
// You are assured that all fileData.xxx properties are updated
// e.g: you may access fileData.file(); fileData.dataURL(); // notice the parenthesis
});

**Comment by safrazik** [comment]
Please let me know if it solves your issue. It's not documented yet as it was added just recently

**Comment by safrazik** [comment]
you can do it with event handlers for the file input (onchange, on drag, etc.)

View:
```html
<input type="file" data-bind="event: {change: triggerFileInputChange}">
<button data-bind="disable: saveButtonDisabled">Save</button>
```

and ViewModel:

```javascript
vm.triggerFileInputChange = function(event){
  vm.saveButtonDisabled(true);
}
// enable savebutton on the subscribe 
vm.fileData.subscribe(function(){
  vm.saveButtonDisabled(false);
});
```

**Comment by equisgroup** [comment]
Looks like it works but i am still facing the issue.

At page load i add some data to fileData this way:
  var dataurl = "data:" + (aVariable.Images[0].TYPE ? aVariable.Images[0].TYPE : "image/jpeg") + ";base64," + aVariable.Images[0].base64;
                                var arr = dataurl.split(',');
                                var mime = arr[0].match(/:(.*?);/)[1];
                                var bstr = atob(arr[1])
                                var n = bstr.length
                                var  u8arr = new Uint8Array(n);
                                while (n--) {
                                    u8arr[n] = bstr.charCodeAt(n);
                                }
                                var archivo = new Blob([u8arr], { type: mime })
                                archivo.lastModifiedDate = new Date();
                                archivo.name = (aVariable.Images[0].NAME ? aVariable.Images[0].NAME : "");
                                self.fileData().fileArray.push(archivo);
                                self.fileData().dataURLArray.push(dataurl);

Form Initial Load:
`"fileData": {
          "fileArray": [
               {
                    "lastModifiedDate": "2016-12-28T17:57:47.163Z",
                    "name": "red.png",
                    "size": 1373,
                    "type": "image/png"
               }
          ],
          "dataURLArray": [
               "data:image/png;base64,iVBORw0KG..."
          ],
          "base64StringArray": [
               "iVBORw0KG..."
          ]
     }
Then i interact with the input setting using ui, selecting 2 files and base64StringArray got 3 elements but fileArray and dataURLArray has 2 as supposed

`"fileData": {
          "fileArray": [
               {
                    "lastModifiedDate": "2016-01-22T14:54:58.969Z",
                    "name": "green.png",
                    "size": 1537,
                    "type": "image/png"
               },
               {
                    "lastModifiedDate": "2016-01-22T14:54:46.407Z",
                    "name": "yellow.png",
                    "size": 1517,
                    "type": "image/png"
               }
          ],
          "dataURLArray": [
               "data:image/png;base64,iVBORw0KGgo...",
               "data:image/png;base64,iVBORw0KGgo..."
          ],
          "base64StringArray": [
               "iVBORw0KGgo...",
               "iVBORw0KGgo...",
               "iVBORw0KGgo..."
          ],
          "file": {
               "lastModifiedDate": "2016-01-22T14:54:58.969Z",
               "name": "green.png",
               "size": 1537,
               "type": "image/png"
          }
     },`

NOTE: I remove characters from the data for size, format message.

Any ideas why?

**Comment by equisgroup** [comment]
Notice: Even if i start without setting initial data on every time that i select an image (or images) base64StringArray is going out of sync with dataURLArray and fileArray increasing it size

**Comment by equisgroup** [comment]
I have tried to understand and follow the code step by step and what i notice is: 
This is true or runs just for DataURL so gets empty but never happens for base64String
  if(index == 0 && fileData[property + 'Array'] && ko.isObservable(fileData[property + 'Array'])){
                        fileData[property + 'Array']([]); 
                    }
then later in code is called  fillDataToProperty(resultParts[1], 'base64String'); and that cause add to base64StringArray but it never got an reset, clear.

**Comment by safrazik** [comment]
I'm having a look at this issue

**Comment by safrazik** [comment]
The issue has been fixed. Your findings were really helpful. You were right about base64StringArray not being set empty. Please let me know if it works for you. Thank you.

**Comment by equisgroup** [comment]
Looks like the number of elements is fine now but
The base64StringArray is out of Sync with fileArray and URLArray based not on number of elements but on elements position in the array. 

Now as a work around i am going to use UrlArray and FileArray that are ok. 1 against 1, 2 against 2

**Comment by equisgroup** [comment]
Is fixed. Why re open?
