### ISSUE TITLE
How to Initialize the knockout-file-upload.

### ISSUE THREAD

**Issue by HakamFostok** [adrotec/knockout-file-bindings#36]
I am using this plugin and I want to initialize the uploader with some image.
I am making an edit scenario for, in another words, I uploaded an image, and when I go to another page to edit, The uploader is showing "no file selected"

here is the code.

    function PhotoVM(id, attachmentId, photoAsString) {
      var self = this;
      self.AttachmentId = ko.observable(attachmentId);
      self.fileData = ko.observable({
          dataURL: ko.observable(),
          base64String: ko.observable(photoAsString),
      });
    }

and here is the HTML

    <div data-bind="fileDrag: fileData">
      <img data-bind="attr: { src: fileData().dataURL }, visible: fileData().dataURL,  style="width:100px;height:100px;">
      <input type="file" data-bind="fileInput: fileData, , customFileInput: {}">
    </div>

**Comment by xabixouu** [comment]
Good afternoon,

I'm trying to do that as well. Did you manage to do it?

Thanks

**Comment by safrazik** [comment]
E.g: a dataURL looks like this:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABE..`
so it needs the type (in this case `image/png`). when you save the image you should save it with metadata at least type. you can get the file metadata by accessing `self.fileData.file()` and type by `self.fileData.file().type` after a file is selected for upload.

So for the initial file preview to work, you need recreate the `dataURL` from type and base64 string
```javascript
var initialData = {
  type: 'image/png',
  base64String: 'iVBORw0KGgoAAAANSUhEUgAABE..'
};

var initialDataUrl = 'data:' + initialData.type + ';base64,' + initialData.base64String;

self.fileData = ko.observable({
      dataURL: ko.observable(initialDataUrl),
  });
```

**Comment by HakamFostok** [comment]
@xabixouu I ended up throwing this plugin and I write my own code.

       ko.bindingHandlers.fileBind = {
        init: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
            var access = ko.utils.unwrapObservable(valueAccessor);
            $(element).on('change', function (e) {
                var file = e.target.files[0];
                var reader = new FileReader();

                reader.onloadend = function (onloadend_e) {
                    var result = reader.result.split(',')[1]; // base 64 encoded file
                    valueAccessor()(result);
                };

                if (file) {
                    reader.readAsDataURL(file);
                }
            });
        },
        update: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

        },
    };

and the html

    <button type="button" onclick="getElementById('Photo').click()"> upload
        <input id="Photo" style="display: none;" accept="image/*" type="file" data-bind="fileBind: arabicFile">
    </button>
    
    <br />
    <img data-bind="attr: { src: 'data:image/jpeg;base64,' + arabicFile() }, validationElement:arabicFile" >
