### ISSUE TITLE
Publish on bower registry

### ISSUE THREAD

**Issue by leftclickben** [adrotec/knockout-file-bindings#4]
This isn't really a code issue but I wasn't sure where else I could put it.

Is it possible for this package to be published on bower, as detailed here?

http://bower.io/docs/creating-packages/

Currently I am using the github URL directly, but it is the only library I am using this way.  Publishing as a bower package would give some direction as to versioning and handling breaking changes.

**Comment by mrsafraz** [comment]
You put in the right place only. I'll do it and close this issue. Thanks for the suggestion

**Comment by mrsafraz** [comment]
It's done! 
`bower install knockout-file-bindings --save`

**Comment by leftclickben** [comment]
Perfect, thanks :-)
