### ISSUE TITLE
does it works with multiple files input ?? 

### ISSUE THREAD

**Issue by manamulya** [adrotec/knockout-file-bindings#5]
<input type="file" id="file" name="image"  multiple= "multiple"  data-bind=" attr: { src: fileData().dataURL },
                            fileInput: fileData, customFileInput: {
                            buttonClass: 'btn btn-success',
                            fileNameClass: 'disabled form-control'
                            } " accept="image/*"/>

**Comment by mrsafraz** [comment]
You mean like `<input type="file" multiple>` ? It doesn't work that way (yet). But you can achieve the same thing by having a dynamic array of fileData instances

**Comment by safrazik** [comment]
It will be added as feature in the next version https://github.com/adrotec/knockout-file-bindings/issues/16
