### ISSUE TITLE
fileDrag does not work in IE

### ISSUE THREAD

**Issue by pvdwaal** [adrotec/knockout-file-bindings#8]
Property "dataset" is not supported in IE and therefor "element.dataset" is undefined.
When replacing it with jQuery's .data() the problem can be fixed.

**Comment by safrazik** [comment]
Can you send a pull request with the fix?

>

**Comment by pvdwaal** [comment]
Sure, will do in a few minutes.

Best regards,

Peter


Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: Muhammad Safraz Razik <notifications@github.com> </div><div>Date:09/09/2015  09:33  (GMT+01:00) </div><div>To: adrotec/knockout-file-bindings <knockout-file-bindings@noreply.github.com> </div><div>Cc: pvdwaal <petervdwaal@hotmail.com> </div><div>Subject: Re: [knockout-file-bindings] fileDrag does not work in IE (#8) </div><div>
</div>
Can you send a pull request with the fix?

>


---

**Comment by safrazik** [comment]
Thank you. Please test everything before you send. Make sure nothing is
broken
